### ISSUE TITLE
No documentation is generated if files have typical header inclusion guards

### ISSUE THREAD

**Issue by brook-milligan** [standardese/standardese#146]
When a header file is processed by standardese no documentation is generated if typical header inclusion guards are present in the file.  In contrast if no inclusion guards are present (clearly not useful) or if #pragma once is present (nonstandard), then documentation is produced.  

The attached tarball contains a set of files: (i) the swap() example from the documentation, (ii) the same with #pragma once, (iii) the same with typical header inclusion guards, (iv) the standardese command line and messages, and (v) the generated *.html output files.  (The functions in the first three files have different names to avoid collisions, but otherwise all is identical.) Standardese produces the same output for the first two, but an empty file (other than the filename) for the third.

[standardese.tar.gz](https://github.com/standardese/standardese/files/3881725/standardese.tar.gz)

**Comment by saraedum** [comment]
The culprit seems to be https://github.com/standardese/standardese/blob/f21bdb4819f3c3a02b9cb7397fc9d004b49575b6/tool/generator.cpp#L37. If I disable fast preprocessing, it works for me.

I have not checked what fast preprocessing actually does. @foonathan, any reason we should not just disable this setting?

**Comment by foonathan** [comment]
> I have not checked what fast preprocessing actually does. I could imagine it takes first #define it sees and uses that always when it sees an #ifdef

Yeah, something like that. cppast needs to do a preprocessing of the file first, in order to handle macros and stuff properly. However, due to the way includes work, the preprocessed file is huge, which can cause slow down. With fast preprocessing, it first figures out all defined macros, and then only preprocesses the main file giving it the list of defined macros. I didn't realize that this breaks include guards...

So disabling it makes it slower, but if it doesn't work otherwise :D
